services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file: 
      - .env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d


volumes:
  postgres-data:

