services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cado
    ports:
      - "5433:5433"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: